# Generated by Django 5.1.4 on 2025-03-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('course_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='questions_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('ipconfig', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=500)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
            ],
        ),
        migrations.CreateModel(
            name='job_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
            ],
        ),
        migrations.CreateModel(
            name='interviewcall_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('updated_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('JOB_REQ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job_request_table')),
            ],
        ),
        migrations.AddField(
            model_name='company_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AddField(
            model_name='candidate_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.CreateModel(
            name='materials_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course_table')),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.CreateModel(
            name='result_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
                ('QUESTIONS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questions_table')),
            ],
        ),
        migrations.CreateModel(
            name='resume_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
            ],
        ),
        migrations.CreateModel(
            name='skills_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=10000)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate_table')),
            ],
        ),
        migrations.AddField(
            model_name='questions_table',
            name='TEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test_table'),
        ),
        migrations.CreateModel(
            name='vacancy_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('no_of_vacancy', models.BigIntegerField()),
                ('details', models.CharField(max_length=300)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table')),
            ],
        ),
        migrations.AddField(
            model_name='test_table',
            name='VACANCY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy_table'),
        ),
        migrations.AddField(
            model_name='job_request_table',
            name='VACANCY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy_table'),
        ),
    ]
