# Generated by Django 5.1.4 on 2025-03-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_table',
            name='COMPANY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.company_table'),
            preserve_default=False,
        ),
    ]
