# Generated by Django 3.2.25 on 2025-03-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback_table_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint_table',
        ),
    ]
