# Generated by Django 3.2.25 on 2025-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_complaint_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions_table',
            old_name='ipconfig',
            new_name='answer',
        ),
    ]
