# Generated by Django 3.2.25 on 2025-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_ipconfig_questions_table_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_table',
            name='Date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification_table',
            name='notification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
