from django.urls import path
from myapp import views

urlpatterns = [
    path('',views.login ),
    path('admin_add_course', views.admin_add_course),
    path('admin_add_materials', views.admin_add_materials),
    path('admin_home', views.admin_home),
    path('admin_company_verify', views.admin_company_verify),
    path('admin_edit_course/<id>', views.admin_edit_course),
    path('admin_edit_materials', views.admin_edit_materials),
    path('admin_view_course', views.admin_view_course),
    path('admin_view_feedback', views.admin_view_feedback),
    path('admin_view_materials', views.admin_view_materials),
    path('admin_view_result', views.admin_view_result),
    path('login_post', views.login_post),
    path('admin_add_course_post', views.admin_add_course_post),
    path('admin_add_materials_post',views.admin_add_materials_post),
    path('company_ragistration', views.company_ragistration),
    path('company_registration_post', views.company_registration_post),
    path('acceptcompany/<int:id>', views.acceptcompany),
    path('rejectedcompany/<int:id>', views.rejectedcompany),
    path('edit_course_post',views.edit_course_post),
    path('admin_search_materials',views.admin_search_materials),
    path('admin_search_course',views.admin_search_course),
    path('edit_materials_post',views.edit_materials_post),
    path('delete_course/<int:id>',views.delete_course),
    path('admin_edit_materials/<int:id>',views.admin_edit_materials),
    path('delete_materilas/<int:id>',views.delete_materilas),
    path('admin_search_company_verify',views.admin_search_company_verify),
    path('admin_view_feedback_search',views.admin_view_feedback_search),
    path('view_applications/<int:id>',views.view_applications),
    path('view_shortlist_applications',views.view_shortlist_applications),




    path('company_home',views.company_home),
    path('change_password',views.change_password),
    path('change_password_post',views.change_password_post),
    path('view_profile',views.view_profile),
    path('edit_profile/<int:id>',views.edit_profile),
    path('edit_profile_post',views.edit_profile_post),
    path('view_vacancy',views.view_vacancy),
    path('send_notification',views.send_notification),
    path('comapny_view_notification',views.comapny_view_notification),
    path('company_add_vacancy',views.company_add_vacancy),
    path('company_edit_vacancy/<int:id>',views.company_edit_vacancy),
    path('edit_vacancy_post',views.edit_vacancy_post),
    path('company_add_vacancy_post',views.company_add_vacancy_post),
    path('delete_vacancy/<int:id>',views.delete_vacancy),
    path('view_test', views.view_test),
    path('add_test', views.add_test),
    path('add_test_post', views.add_test_post),
    path('edit_test/<int:id>', views.edit_test),
    path('reply_complaint/<int:id>', views.reply_complaint),
    path('edit_test_post', views.edit_test_post),
    path('delete_test/<int:id>', views.delete_test),
    path('view_questions/<testid>', views.view_questions),
    path('add_question', views.add_question),
    path('add_question_post', views.add_question_post),
    path('view_result', views.view_result),
    path('view_feedback', views.view_feedback),
    path('view_feedback_search', views.view_feedback_search),
    path('view_complaint', views.view_complaint),
    path('view_resume', views.view_resume),
    path('edit_question/<int:id>', views.edit_question),
    path('delete_questions/<int:id>', views.delete_questions),
    path('edit_question_post', views.edit_question_post),
    path('replypost', views.replypost),
    path('interviecall/<reqid>',views.interviecall),
    path('interviewCallpost',views.interviewCallpost),



    path('userhome', views.userhome),
    path('user_view_profile', views.user_view_profile),
    path('edit_profile_user', views.edit_profile_user),
    path('edit_profile_action', views.edit_profile_action),
    path('user_registration', views.user_registration),
    path('user_upload_resume', views.user_upload_resume),
    path('user_upload_resume_action', views.user_upload_resume_action),
    path('user_view_resume', views.user_view_resume),
    path('user_edit_resume', views.user_edit_resume),
    path('logout', views.logout),
    path('registrationcode', views.registrationcode),
    path('user_view_application', views.user_view_application),
    path('view_candidate_vacancy', views.view_candidate_vacancy),
    path('candidate_submit_answer', views.candidate_submit_answer),
    path('apply_for_vacancy/<id>', views.apply_for_vacancy),
    path('user_view_test/<id>', views.user_view_test),
    # path('and_change_password_post', views.and_change_password_post),
    path('sendfeedback/<id>', views.sendfeedback),
    path('sendfeedback_action/<id>', views.sendfeedback_action),
    path('view_result_canditate', views.view_result_canditate),
    path('view_candidate_question', views.view_candidate_question),
    path('view_candidate_question2', views.view_candidate_question2),
    path('user_view_test', views.user_view_test),
    path('view_request_status', views.view_request_status),
    path('submit_answers', views.submit_answers),
    path('start_quiz/<test_id>', views.start_quiz),
    path('user_view_interview_call/<id>', views.user_view_interview_call),
    path('user_view_notification', views.user_view_notification),


]
